IF EXISTS (SELECT name FROM sys.databases WHERE name = 'ORDER_DDS')
BEGIN
    USE master;
    ALTER DATABASE ORDER_DDS
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

    DROP DATABASE ORDER_DDS;
END;

CREATE DATABASE ORDER_DDS;
